import { base44 } from '@base44/core';

export default async function generateDailyContent(req: Request) {
  try {
    const contentDrafts = [
      {
        title: "Busy Parent Morning Chaos → Clean Home Peace",
        audience: "Families",
        pillar: "Transformation",
        hook: "Before: 6am wake-up, toys everywhere, no time to breathe. After: Same morning, but your home is actually clean.",
        primary_caption: "It's not about being lazy. It's about choosing what matters. Spend Saturday morning with your kids instead of scrubbing floors. That's what PureTask customers tell us.",
        short_caption: "Tired of choosing between a clean house and a life? That's the point of PureTask.",
        long_caption: "Saturday morning. You could spend 4 hours deep-cleaning. Or you could spend 4 hours with your family. PureTask handles the cleaning part—so you handle the living part. Real customers, real results. Book now.",
        cta_1: "See how it works",
        cta_2: "Check availability in your area",
        cta_3: "Browse cleaner profiles",
        image_prompt: "Split-screen: left side shows cluttered living room with toys scattered, tired parent in background; right side shows same room immaculate and bright, same parent relaxed with kids laughing",
        video_prompt: "30-second reel: Parent stressed about mess → PureTask cleaners arrive → time-lapse of cleaning → parent with kids playing in clean space, smiling",
        script_15sec: "Saturday. You can clean, or you can live. PureTask customers choose to live. Real professionals. Real trust. Real time back. Book in 60 seconds.",
        script_30sec: "Your home doesn't have to be the thing stealing your time. PureTask connects you with vetted, background-checked cleaners who actually care. Real homes. Real results. Real people choosing their families over floor wax. Book a cleaning in under a minute.",
        comment_replies: "Q: How do you vet cleaners? A: Every cleaner is background-checked, ID verified, and rated by customers. Trust is non-negotiable. | Q: Can I pick my cleaner? A: Yes. You browse profiles, see reviews, and book the person you want. | Q: What if something gets broken? A: We're insured. Simple.",
        platform_x: "yes",
        platform_instagram: "yes",
        platform_facebook: "yes",
        platform_linkedin: "no",
        platform_tiktok: "yes",
        platform_pinterest: "yes",
        blog_post: "no",
        status: "Pending Approval",
        week_tag: "Week of Apr 8",
        campaign_tag: "Families - Transformation",
        city: "National",
        clarity_score: 9,
        relatability_score: 9,
        conversion_score: 8
      },
      {
        title: "Working Professional Time Scarcity Pain Point",
        audience: "Working Professionals",
        pillar: "Convenience",
        hook: "You're billing clients by the hour. Why are you spending it on your own floors?",
        primary_caption: "Real talk: professionals don't clean their own homes. They hire people who are good at it. That's not lazy. That's efficient.",
        short_caption: "Your time is worth money. Stop trading it for dust.",
        long_caption: "You manage projects. You solve problems. You create value. And then you come home and... scrub? That's not a life, that's a schedule conflict. PureTask cleaners handle the floors so you handle what only you can do.",
        cta_1: "Book a cleaner today",
        cta_2: "See pricing",
        cta_3: "Check your neighborhood",
        image_prompt: "Professional at desk looking at watch, stressed; clock morphs into clean home; professional relaxed on couch with a drink, smiling",
        video_prompt: "15-second video: Quick montage of busy work moments (laptop, phone, meetings) → transition to home → cleaner working → professional arrives to clean home, relaxes",
        script_15sec: "Your hourly rate is higher than the cost of a cleaner. Do the math. PureTask. Book now.",
        script_30sec: "You bill by the hour. You manage teams. You solve problems. Why are you trading that time for cleaning? PureTask connects you with professionals who clean better than you do—so you can focus on what you're actually good at.",
        comment_replies: "Q: How often can I book? A: Weekly, biweekly, monthly—whatever works for your schedule. | Q: Are cancellations easy? A: Yes. 24-hour cancellation policy, no penalties. | Q: What gets cleaned? A: Bathrooms, kitchen, floors, common areas. Full service.",
        platform_x: "yes",
        platform_instagram: "yes",
        platform_facebook: "yes",
        platform_linkedin: "yes",
        platform_tiktok: "no",
        platform_pinterest: "no",
        blog_post: "no",
        status: "Pending Approval",
        week_tag: "Week of Apr 8",
        campaign_tag: "Professionals - Convenience",
        city: "National",
        clarity_score: 9,
        relatability_score: 8,
        conversion_score: 9
      },
      {
        title: "Cleaner Safety & Trust Reassurance",
        audience: "Busy Homeowners",
        pillar: "Trust",
        hook: "Let a stranger into your home? Only if you actually know them.",
        primary_caption: "Background-checked. ID verified. Reviewed by real customers. Insured. That's how PureTask cleaners roll. Your home isn't a gamble.",
        short_caption: "Real background checks. Real reviews. Real peace of mind.",
        long_caption: "You've worked hard for your home. It's not just a space—it's your retreat. That's why PureTask doesn't just hire cleaners. We vet them. Background check. ID verification. Customer ratings. Insurance. That's trust you can actually feel.",
        cta_1: "Read real customer reviews",
        cta_2: "Learn our vetting process",
        cta_3: "Book with confidence",
        image_prompt: "Home interior with warm lighting; overlay of checkmark icons for 'background check', 'ID verified', 'insured', 'customer rated'; cleaner smiling with clipboard",
        video_prompt: "30-second explainer: Close-ups of vetting steps (background check ✓, ID verification ✓, customer review ✓, insurance ✓) → cleaner enters home professionally → customer gives thumbs up",
        script_15sec: "Background-checked. Verified. Insured. Rated by your neighbors. That's a PureTask cleaner.",
        script_30sec: "Your home deserves better than a gamble. Every PureTask cleaner is background-checked, ID verified, customer-rated, and insured. You're not taking a chance. You're making a choice.",
        comment_replies: "Q: What if there's damage? A: We're fully insured. You're protected. | Q: Can I see reviews before booking? A: Absolutely. Every cleaner has verified customer ratings. | Q: What's the vetting timeline? A: 7-10 days. Quality over speed.",
        platform_x: "yes",
        platform_instagram: "yes",
        platform_facebook: "yes",
        platform_linkedin: "no",
        platform_tiktok: "yes",
        platform_pinterest: "no",
        blog_post: "no",
        status: "Pending Approval",
        week_tag: "Week of Apr 8",
        campaign_tag: "Trust - Reassurance",
        city: "National",
        clarity_score: 9,
        relatability_score: 8,
        conversion_score: 8
      },
      {
        title: "Cleaner Recruitment: Flexible Work Freedom",
        audience: "Cleaners / Gig Workers",
        pillar: "Recruitment",
        hook: "Tired of invisible gig work? PureTask values you. Real pay. Real respect. Real reviews.",
        primary_caption: "You're good at what you do. Why work for a platform that treats you like a number? PureTask cleaners earn real money, build real client relationships, and get real recognition. No algorithms. No invisibility. Just you, your work, and customers who appreciate it.",
        short_caption: "Gig work doesn't have to mean invisible work. Join PureTask.",
        long_caption: "You're a professional. Not a contractor. Not a number. A professional. PureTask was built for people like you—cleaners who care about quality, want flexible hours, and deserve to be seen. Fair pay. Real reviews. Direct client relationships. Your reputation matters here.",
        cta_1: "Apply to clean with PureTask",
        cta_2: "See cleaner earnings",
        cta_3: "Read cleaner testimonials",
        image_prompt: "Portrait of confident cleaner in professional gear, smiling; background shows happy customers and five-star ratings; clean, modern aesthetic",
        video_prompt: "30-second video: Cleaner doing quality work → customer satisfaction → cleaner checking their earnings and ratings → cleaner smiling, proud",
        script_15sec: "PureTask pays you fairly. Treats you professionally. And customers see your name. That's how it should be.",
        script_30sec: "You're not looking for invisible gig work. You're looking for a platform that actually respects your skills. PureTask cleaners earn fair pay, work flexible hours, build real client relationships, and get recognized for their work. Apply today.",
        comment_replies: "Q: How much do cleaners earn? A: $25-45/hour depending on service and location. Plus tips. | Q: Can I choose my clients? A: Yes. You see the job details and decide. | Q: What about equipment? A: We provide cleaning supplies or you use your own—your choice.",
        platform_x: "no",
        platform_instagram: "yes",
        platform_facebook: "yes",
        platform_linkedin: "yes",
        platform_tiktok: "yes",
        platform_pinterest: "no",
        blog_post: "no",
        status: "Pending Approval",
        week_tag: "Week of Apr 8",
        campaign_tag: "Recruitment - Workers",
        city: "National",
        clarity_score: 8,
        relatability_score: 9,
        conversion_score: 8
      },
      {
        title: "Cleaner Recruitment: Steady Income Path",
        audience: "Cleaners / Gig Workers",
        pillar: "Recruitment",
        hook: "Gig work without the gig economy stress? Build real recurring clients on PureTask.",
        primary_caption: "Weekly regulars. Reliable income. Your own schedule. PureTask cleaners aren't chasing jobs—they're building a client base that keeps coming back. That's stability without sacrifice.",
        short_caption: "Gig work that actually feels stable. Real recurring clients. Real income.",
        long_caption: "The problem with most gig platforms: you're always hunting for the next job. PureTask is different. Build relationships with real clients who book you regularly. Weekly recurring cleanings. Monthly deep cleans. Referrals from satisfied customers. That's predictable income.",
        cta_1: "Start earning this week",
        cta_2: "Learn how recurring work works",
        cta_3: "Chat with an existing cleaner",
        image_prompt: "Calendar view with recurring bookings highlighted; cleaner smiling while looking at a steady schedule; income chart trending upward",
        video_prompt: "30-second video: Cleaner talking about getting same regular clients → booking calendar filling up → steady weekly income → cleaner at home relaxed, knowing next week is booked",
        script_15sec: "Tired of hunting jobs? PureTask customers book you weekly. Recurring income. Real stability.",
        script_30sec: "Gig work shouldn't mean constant uncertainty. PureTask cleaners build recurring client relationships. That means weekly bookings, predictable income, and the freedom to actually plan your life.",
        comment_replies: "Q: How many recurring clients can I get? A: Depends on your capacity and effort. Most cleaners have 5-15 recurring clients within 3 months. | Q: What if a client cancels? A: You keep other clients. The PureTask app shows you open jobs too. | Q: Can I set my own rates? A: Base rates are set by PureTask, but you get tips and can offer add-ons.",
        platform_x: "no",
        platform_instagram: "yes",
        platform_facebook: "yes",
        platform_linkedin: "yes",
        platform_tiktok: "yes",
        platform_pinterest: "no",
        blog_post: "no",
        status: "Pending Approval",
        week_tag: "Week of Apr 8",
        campaign_tag: "Recruitment - Workers",
        city: "National",
        clarity_score: 8,
        relatability_score: 8,
        conversion_score: 7
      },
      {
        title: "Local Market Launch: San Francisco Bay Area",
        audience: "Busy Homeowners",
        pillar: "Local Relevance",
        hook: "Bay Area homes deserve Bay Area-level service. PureTask is now booking in your neighborhood.",
        primary_caption: "Silicon Valley runs on efficiency. Your home should too. PureTask is live in SF, Oakland, and the Peninsula. Professional cleaners, 24-hour booking, real customer reviews. Meet your neighborhood's cleaners.",
        short_caption: "PureTask is now in the Bay. Book your cleaner today.",
        long_caption: "You know how it goes in the Bay—everyone's busy, no one's local, and good help is impossible to find. PureTask just changed that. Vetted cleaners live in your neighborhood. They know the area. Same-week availability. Book now.",
        cta_1: "See available cleaners near you",
        cta_2: "Book your first cleaning",
        cta_3: "Read Bay Area customer reviews",
        image_prompt: "Golden Gate Bridge or Bay Area skyline; overlay of map pins showing cleaner locations; city lights, modern aesthetic",
        video_prompt: "15-second video: Bay Area landmarks → map showing cleaner coverage → customer booking on phone → cleaner arriving professionally → customer satisfied",
        script_15sec: "PureTask is here. Your neighborhood. Your cleaners. Book now.",
        script_30sec: "Bay Area professionals don't have time to clean. That's why PureTask is here. Local cleaners, fast booking, real reviews. Your home, your neighbors, your trust.",
        comment_replies: "Q: What areas are covered? A: SF proper, Oakland, the Peninsula, and the East Bay. More neighborhoods added weekly. | Q: How fast is availability? A: 24-48 hours in most areas. Same-day in high-demand zones. | Q: Do you cover my specific block? A: Check the app. 95% coverage in covered areas.",
        platform_x: "yes",
        platform_instagram: "yes",
        platform_facebook: "yes",
        platform_linkedin: "no",
        platform_tiktok: "no",
        platform_pinterest: "yes",
        blog_post: "no",
        status: "Pending Approval",
        week_tag: "Week of Apr 8",
        campaign_tag: "Local - Bay Area Launch",
        city: "San Francisco, CA",
        clarity_score: 8,
        relatability_score: 8,
        conversion_score: 8
      },
      {
        title: "Short-Form Video Concept: Before/After Transformation",
        audience: "Families",
        pillar: "Proof",
        hook: "Nobody asks 'how do you have time to clean?' They ask 'how is your home always this clean?'",
        primary_caption: "TikTok/Reel caption: POV: You have a PureTask cleaner. ✨ Real customer homes. Real transformations. Real results.",
        short_caption: "POV: Your life just got easier.",
        long_caption: "This isn't magic. It's efficiency. Real homes. Real customers. Real before/afters. That's the PureTask difference.",
        cta_1: "See more transformations",
        cta_2: "Book your transformation",
        cta_3: "Watch cleaner reviews",
        image_prompt: "Split-screen before/after: cluttered living room on left, immaculate identical space on right; bright, clean aesthetic; text overlay 'POV: You have a PureTask cleaner'",
        video_prompt: "30-second TikTok/Reel: Quick cuts of messy spaces → PureTask cleaner arriving → time-lapse of cleaning → beautiful finished space → satisfied customer reaction (smile, thumbs up, taking photo)",
        script_15sec: "This is a real home. This is a real transformation. This is a real PureTask customer.",
        script_30sec: "Nobody has time for this anymore. That's why real people book real cleaners. Watch a real home transformation. Then book yours.",
        comment_replies: "Q: Is this a real home? A: Yes. Real customers. Real before and afters. | Q: How long does it take? A: Depends on size, but most 2-3BR homes take 3-4 hours. | Q: Can I request specific focus areas? A: Absolutely. Customize your cleaning before booking.",
        platform_x: "no",
        platform_instagram: "yes",
        platform_facebook: "no",
        platform_linkedin: "no",
        platform_tiktok: "yes",
        platform_pinterest: "no",
        blog_post: "no",
        status: "Pending Approval",
        week_tag: "Week of Apr 8",
        campaign_tag: "Proof - Transformation",
        city: "National",
        clarity_score: 8,
        relatability_score: 9,
        conversion_score: 8
      },
      {
        title: "Senior Care Angle: Aging in Place with Dignity",
        audience: "Seniors",
        pillar: "Trust",
        hook: "A clean home is part of staying independent. PureTask makes that possible.",
        primary_caption: "Aging in place doesn't mean living with a mess. PureTask cleaners are patient, respectful, and thorough. Keep your independence. Keep your dignity. Keep your home clean.",
        short_caption: "Stay independent. Stay in your home. Let us handle the cleaning.",
        long_caption: "You want to age in your own home, on your own terms. That means having help you can trust. PureTask cleaners are vetted, patient, and respectful. They're not there to judge. They're there to help you keep your independence and your dignity.",
        cta_1: "Learn more about senior care",
        cta_2: "Book a consultation",
        cta_3: "See testimonials from seniors",
        image_prompt: "Warm, respectful image: senior in clean, bright home; cleaner helping respectfully in background; peaceful, dignified atmosphere; plants, natural light",
        video_prompt: "30-second video: Senior in home they love → PureTask cleaner arrives respectfully → gentle interaction → home is clean and tidy → senior relaxed, independent",
        script_15sec: "Stay in your home. Let us handle the floors. That's independence.",
        script_30sec: "You've built your life. Your home is part of that. PureTask helps you keep it the way you like it—without hiring someone you don't know. Vetted, patient, respectful cleaners. That's aging with dignity.",
        comment_replies: "Q: Are cleaners trained for senior homes? A: Yes. All cleaners are trained in respect, patience, and accessibility. | Q: What if I need help beyond cleaning? A: We're cleaners, not caregivers. But we respect your needs and communicate with family. | Q: How often should I book? A: Depends on your health and mobility. We recommend weekly or biweekly.",
        platform_x: "no",
        platform_instagram: "yes",
        platform_facebook: "yes",
        platform_linkedin: "no",
        platform_tiktok: "no",
        platform_pinterest: "yes",
        blog_post: "no",
        status: "Pending Approval",
        week_tag: "Week of Apr 8",
        campaign_tag: "Seniors - Trust & Independence",
        city: "National",
        clarity_score: 8,
        relatability_score: 8,
        conversion_score: 7
      }
    ];

    // Create all drafts
    const created = await base44.asServiceRole.entities.ContentDraft.create(contentDrafts);

    return {
      status: 200,
      body: {
        success: true,
        message: `Generated ${contentDrafts.length} content drafts for today`,
        count: contentDrafts.length,
        drafts: created
      }
    };
  } catch (error) {
    return {
      status: 500,
      body: {
        success: false,
        error: error.message
      }
    };
  }
}
