import { base44 } from '@base44/core';

// Generate weekly strategy changelog and commit to GitHub
export default async function weeklyStrategyReport(req: Request) {
  const GITHUB_TOKEN = Deno.env.get('GITHUB_TOKEN');
  const REPO = 'PURETASK/automation---social-media-content-campaign-for-puretask';
  const BASE_URL = `https://api.github.com/repos/${REPO}/contents`;

  if (!GITHUB_TOKEN) {
    return new Response(JSON.stringify({ error: 'GITHUB_TOKEN not set' }), { status: 500 });
  }

  // Get this week's content data
  const today = new Date();
  const weekStart = new Date(today);
  weekStart.setDate(today.getDate() - today.getDay());
  const weekStartStr = weekStart.toISOString().split('T')[0];

  try {
    // Fetch content drafts from this week
    const drafts = await base44.asServiceRole.entities.ContentDraft.list({
      limit: 100
    });

    const weekDrafts = drafts.filter((d: any) => {
      const created = new Date(d.created_date);
      return created >= weekStart;
    });

    // Fetch performance data
    const posted = await base44.asServiceRole.entities.PostPerformance.list({
      limit: 100
    });

    const weekPosted = posted.filter((p: any) => {
      const postedDate = new Date(p.posted_at);
      return postedDate >= weekStart;
    });

    // Calculate stats
    const pillarCounts: Record<string, number> = {};
    const audienceCounts: Record<string, number> = {};
    let totalScore = 0;
    let scoredCount = 0;

    weekDrafts.forEach((d: any) => {
      pillarCounts[d.pillar] = (pillarCounts[d.pillar] || 0) + 1;
      audienceCounts[d.audience] = (audienceCounts[d.audience] || 0) + 1;
      
      if (d.clarity_score && d.relatability_score && d.conversion_score) {
        totalScore += (d.clarity_score + d.relatability_score + d.conversion_score) / 3;
        scoredCount += 1;
      }
    });

    const avgScore = scoredCount > 0 ? (totalScore / scoredCount).toFixed(1) : 'N/A';

    // Get top performers
    const topPerformers = weekPosted
      .sort((a: any, b: any) => (b.performance_score || 0) - (a.performance_score || 0))
      .slice(0, 3);

    // Build markdown report
    let report = `# Weekly PureTask Content Strategy Report\n\n`;
    report += `**Week of ${weekStartStr}**\n\n`;
    
    report += `## 📊 This Week's Output\n`;
    report += `- **Total Drafts Generated**: ${weekDrafts.length}\n`;
    report += `- **Posted**: ${weekPosted.length}\n`;
    report += `- **Average Quality Score**: ${avgScore}\n\n`;

    report += `## 🎯 Content by Pillar\n`;
    Object.entries(pillarCounts).forEach(([pillar, count]) => {
      report += `- ${pillar}: ${count}\n`;
    });
    report += `\n`;

    report += `## 👥 Content by Audience\n`;
    Object.entries(audienceCounts).forEach(([audience, count]) => {
      report += `- ${audience}: ${count}\n`;
    });
    report += `\n`;

    if (topPerformers.length > 0) {
      report += `## 🏆 Top Performers\n`;
      topPerformers.forEach((p: any, i: number) => {
        report += `${i + 1}. **${p.content_title}** (${p.platform}) - Score: ${p.performance_score}\n`;
        report += `   - Reach: ${p.reach || 'N/A'} | Engagement: ${p.engagement_rate || 'N/A'}\n`;
      });
      report += `\n`;
    }

    report += `## 🔄 What's Next\n`;
    report += `- Next audience focus: Monitor performance trends\n`;
    report += `- Continue testing platform-specific adaptations\n`;
    report += `- Analyze winning hook patterns for next week's brainstorm\n\n`;

    report += `---\n`;
    report += `*Auto-generated by PureTask Content Engine. Generated: ${new Date().toISOString()}\n`;

    // Push to GitHub
    const filename = `weekly-reports/week-${weekStartStr.replace(/-/g, '')}-report.md`;
    const encodedContent = btoa(unescape(encodeURIComponent(report)));

    let sha = null;
    try {
      const checkRes = await fetch(`${BASE_URL}/${filename}`, {
        headers: { 'Authorization': `Bearer ${GITHUB_TOKEN}` }
      });
      if (checkRes.ok) {
        sha = (await checkRes.json()).sha;
      }
    } catch (_) {}

    const payload: Record<string, string> = {
      message: `Weekly strategy report: ${weekStartStr}`,
      content: encodedContent
    };
    if (sha) payload.sha = sha;

    const res = await fetch(`${BASE_URL}/${filename}`, {
      method: 'PUT',
      headers: {
        'Authorization': `Bearer ${GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github+json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    });

    const data = await res.json();
    return new Response(
      JSON.stringify({
        success: res.ok,
        report_file: filename,
        stats: {
          drafts_generated: weekDrafts.length,
          posts_published: weekPosted.length,
          average_score: avgScore
        },
        github_url: data?.content?.html_url || null
      }),
      { headers: { 'Content-Type': 'application/json' } }
    );
  } catch (e) {
    return new Response(JSON.stringify({ error: String(e) }), { status: 500 });
  }
}
